"""RAG runtime configuration."""

from __future__ import annotations

from ..config import (
    ANSWER_MODEL,
    ANSWER_NUM_PREDICT,
    ENABLE_WEB_SEARCH,
    INTENT_MODEL,
    INTENT_NUM_PREDICT,
    LLM_TIMEOUT,
    OLLAMA_BASE_URL,
    OLLAMA_TEMPERATURE,
    TAVILY_API_KEY,
    TAVILY_API_URL,
    TOP_K,
    WEB_SEARCH_API_KEY,
    WEB_SEARCH_API_URL,
    WEB_SEARCH_BLOCKLIST_DOMAINS,
    WEB_SEARCH_LIMIT,
    WEB_SEARCH_TIMEOUT,
)

__all__ = [
    "ANSWER_MODEL",
    "ANSWER_NUM_PREDICT",
    "ENABLE_WEB_SEARCH",
    "INTENT_MODEL",
    "INTENT_NUM_PREDICT",
    "LLM_TIMEOUT",
    "OLLAMA_BASE_URL",
    "OLLAMA_TEMPERATURE",
    "TAVILY_API_KEY",
    "TAVILY_API_URL",
    "TOP_K",
    "WEB_SEARCH_API_KEY",
    "WEB_SEARCH_API_URL",
    "WEB_SEARCH_BLOCKLIST_DOMAINS",
    "WEB_SEARCH_LIMIT",
    "WEB_SEARCH_TIMEOUT",
]
